# Enforce Ruff (lint), isort (imports), and Black (format) on each commit.
# Using local hooks so versions are controlled by your environment/pyproject.
# Run once:   py -m pre_commit install
# Run now:    py -m pre_commit run --all-files

repos:
  - repo: local
    hooks:
      - id: isort
        name: isort (imports)
        entry: py
        language: system
        types: [python]
        args: ["-m", "isort"]

      - id: black
        name: black (format)
        entry: py
        language: system
        types: [python]
        args: ["-m", "black"]

      - id: ruff
        name: ruff (lint, autofix)
        entry: py
        language: system
        types: [python]
        args: ["-m", "ruff", "check", "--fix"]
